defaults: &defaults
  docker:
    - image: jtredoux/node-aws:latest

version: 2
jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: npm run set-config
      - persist_to_workspace:
          root: .
          paths:
            - data/*

  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls -la
      - run: cat data/classesByDay.json

workflows:
  version: 2
  release_branches:
    jobs:
      - init
      - install:
          requires:
            - init
      - deploy:
          requires:
            - install
