defaults: &defaults
  docker:
    - image: jtredoux/node-aws:latest

version: 2
jobs:
  set-config:
    <<: *defaults
    steps:
      - checkout
      - run: npm run set-config
      - persist_to_workspace:
          root: .
          paths:
            - data/*

  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*

workflows:
  version: 2
  release_branches:
    jobs:
      - set-config
      - install:
          requires:
            - set-config